# CS82 - Introduction to Machine Learning

## Homework 3


### Submission

email a completed copy of this notebook to danny@ktbyte.com with subject:
`[CS82] HW3 - Student Name`

## Description

To complete this homework you will need to read:
* [Handout 3](https://content.ktbyte.com/cs82/20sp/handout/3.html)
* [Workshop 3](https://content.ktbyte.com/cs82/20sp/workshop/ws_3.ipynb)
* [Handout 4](https://content.ktbyte.com/cs82/20sp/handout/4.html)

**Tasks** are to be performed and their output saved
**Questions** are to be answered and their output saved


### TASK

Create three functions, with the following restrictions. Must **NOT** use numpy. Input will be python lists. The lists can contain numbers, strings, or other unspecified types. You must check and handle for as many cases as you can think of (including dimension mismatch). Functions must work as close to numpy version as possible. 

* `def dot(x,y)` calculates the dot product between any two given vectors
* `def cross(x,y)` calculates the cross product between any two given vectors
* `def matmul(x,y)` calculates the matrix multiplication product between any two given matrices
* `def transpose(x)` calculates the transpose of a matrix


In [7]:
def dot(x,y):
    if len(x) != len(y): return 'Error!'
    sum = 0
    for i in range(len(x)):
        sum += x[i] * y[i]
    return sum
        
def cross(x,y):
    if len(x) != 3 or len(y) != 3: return 'Error!'
    one = x[1]*y[2] - x[2]*y[1]
    two = x[2]*y[0] - x[0]*y[2]
    three = x[0]*y[1] - x[1]*y[0]
    return list(one,two,three)
    
def matmul(x,y):
    if len(x[0]) != len(y): return 'Error!'
    mat = []
    for i in range(len(y[0])):
        sum = 0
        for j in range(len(x)):
            sum += x[j] * y[j][i]
        mat.append(sum)
    return mat
    
def transpose(x):
    return list(zip(*x))
    

### Question

What edge cases did you consider for your input and how did you handle malformed data?

**Answer**
For cross product I pad 3 zeros at the end of the array and clip it to be of size 3. That is because cross product is only defined for 3 dimensional space. Larger vectors will be clipped. 

For dot product I check if the vector shapes match, if they don't I return None

For matrix multiplication I check to see if the dimensions match the definition of matrix multiplication

### TASK

Create a function that calculates the conditional probability $P(A|A+B<M)$, for the roll of two die A and B. That is the probability of rolling a total of less than N given the value of A.

We are given as input the matrix of the sample space for 2 N-Face die (each dice has N faces where N is the size of the matrix). Each entry in the matrix is the result of adding the outcome from dice A and B. The input to the function is the value of the first dice A and the value of M as well as the sample space.

**Conditions**
The index of the sample space matrix signifies the value of A or B. There will be no missing indexes. The values of A and B will then range from 1 to N (however you need to account for 0 indexing)

**Example** 

Example of a sample space for rolling 2 die that each has 6-faces.

$$
\begin{bmatrix}
	 2	& 3	& 4	& 5	& 6	& 7 \\
	 3	& 4	& 5	& 6	& 7	& 8 \\
	 4	& 5	& 6	& 7	& 8	& 9 \\
	 5	& 6	& 7	& 8	& 9	& 10 \\
	 6	& 7	& 8	& 9	& 10	& 11 \\
	 7	& 8	& 9	& 10	& 11	& 12\\
\end{bmatrix}
$$

To make it easier I have created a function that generates a sample space for two N-faced die

```python
def generate_matrix(N=6):
    import numpy as np
    A=np.array([list(range(1,N+1))]*N)
    B=np.array([list(range(1,N+1))]*N)
    return A+B.transpose()
```

The function above generates the outcomes of a single dice, converts them into a matrix such that outcomes are 1 through N for each row. 

It then adds the transpose of a copy of the same matrix (since one dice is in the columns and another in the rows a transpose inverts rows with columns).

Please print and examine the above function to make sure you understand the logic behind it.

In [11]:
def generate_matrix(N=6):
    import numpy as np
    A=np.array([list(range(1,N+1))]*N)
    B=np.array([list(range(1,N+1))]*N)
    return A+B.transpose()

obj = generate_matrix()

for i in obj:
    print(i)

[2 3 4 5 6 7]
[3 4 5 6 7 8]
[4 5 6 7 8 9]
[ 5  6  7  8  9 10]
[ 6  7  8  9 10 11]
[ 7  8  9 10 11 12]


### TASK

Create a function that calculates the derivative of a polynomial. The input to that function are two vectors, the coefficients of a polynomial and the power of each term on that polynomial. The output should be the coefficients and powers of the derivative function.

**Definition**

A polynomial is a function of the form $f(x)=m_1x^{p_1}+\dots+m_nx^{p_n}$

* $m_1$ through $m_n$ are the coefficients of the polynomial

* $p_1$ throught $p_n$ is the power of the polynomial.

**Conditions**

For our problem we can't have values of repeating powers. But we can have values of repeating coefficients. A term can also be 0, that is when the coefficient is 0. A term can also be a constant that is when the power is of 0, the value of that constant will then be the value of the coefficient. All power coefficients are positive or 0.

**Example**

m vector
```
m=[0,100,2,38,3]
```
p vector
```
p=[2,100,4,5,0]
```
is the resulting polynomial
$$
 f(x)=0 x^{2}+100x^{100}+2x^4+38x^5+3x^0=3+100x^{100}+2x^4+38x^5
$$

The derivative is then

$$
f'(x)=10000x^{99}+8x^3+190x^4
$$

**Do not use any library to calculate the derivative**

### Optional

Calculate the minima and maxima for the derivative function.

**Tip** You can find the minima/maxima graphically by providing a range of values to the derivative polynomial you calculated and seeing where it is close to 0. e.g. 0.0001 Try with simple examples such as $x^2$

In [15]:
def deriv(x,y):
    coef = []
    pow = []
    for i in range(len(x)):
        if x[i] == 0 or y[i] == 0: continue
        coef.append(x[i] * y[i])
        pow.append(y[i] - 1)
        
    return (coef, pow)

print(deriv([0,100,2,38,3], [2,100,4,5,0]))

([10000, 8, 190], [99, 3, 4])
